import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {randomUUID,randomBytes} from 'node:crypto';
import {WebSocketServer,WebSocket} from 'ws';
import {setup,step} from './game.js';
const rooms=new Map();
const server=http.createServer(async(req,res)=>{const path=req.url.split('?')[0];if(path==='/healthz'){res.writeHead(200);return res.end('ok');}const vendor={'/three.module.js':'three.module.js','/three.core.js':'three.core.js'};if(vendor[path]){res.setHeader('Content-Type','text/javascript');return res.end(await readFile(new URL('./node_modules/three/build/'+vendor[path],import.meta.url)));}const files={'/':['index.html','text/html'],'/app.js':['app.js','text/javascript'],'/scene.js':['scene.js','text/javascript'],'/style.css':['style.css','text/css']};if(!files[path]){res.writeHead(404);return res.end('Not found');}try{res.setHeader('Content-Type',files[path][1]+'; charset=utf-8');res.end(await readFile(new URL('./public/'+files[path][0],import.meta.url)));}catch{res.writeHead(500);res.end('Server error');}});
const wss=new WebSocketServer({server,maxPayload:2048});
const send=(ws,data)=>{if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data));};
function state(r){for(const p of r.players)send(p.ws,{type:'state',code:r.code,mode:r.mode,you:p.id,players:r.players.map(({id,name,team,ready,disconnectedAt})=>({id,name,team,ready,connected:!disconnectedAt})),paused:!!r.pausedAt,reconnectDeadline:r.pausedAt?Math.min(...r.players.filter(p=>p.disconnectedAt).map(p=>p.disconnectedAt+30000)):0,phase:r.phase,bodies:r.bodies,score:r.score,deadline:r.deadline+(r.pausedAt?Date.now()-r.pausedAt:0),remaining:Math.max(0,Math.ceil((r.endAt-(r.pausedAt||Date.now()))/1000)),winner:r.winner,aims:Object.fromEntries([...r.aims].filter(([id])=>r.players.find(q=>q.id===id)?.team===p.team)),locked:[...r.aims.keys()]});}
function aimPhase(r){r.phase='aim';r.aims.clear();r.deadline=Date.now()+30000;}
function start(r){r.score=[0,0];r.bodies=setup(r.players);r.endAt=Date.now()+180000;r.winner=null;aimPhase(r);}
function launch(r){for(const b of r.bodies){const a=r.aims.get(b.id);if(a){b.vx=a.x*700;b.vy=a.y*700;}}r.phase='move';r.deadline=Date.now()+4000;}
function disconnect(ws){const r=rooms.get(ws.room),p=r?.players.find(p=>p.ws===ws);if(!p)return;p.ws=null;p.disconnectedAt=Date.now();r.pausedAt ||= Date.now();state(r);}
function resumeClock(r){if(r.pausedAt&&!r.players.some(p=>p.disconnectedAt)){const delay=Date.now()-r.pausedAt;r.deadline+=delay;r.endAt+=delay;r.pausedAt=0;}}
function leave(ws){const r=rooms.get(ws.room);if(!r)return;r.players=r.players.filter(p=>p.ws!==ws);ws.room=null;if(!r.players.length){rooms.delete(r.code);return;}r.phase='lobby';r.bodies=[];r.aims.clear();r.players.forEach(p=>p.ready=false);resumeClock(r);state(r);}
wss.on('connection',ws=>{ws.id=randomUUID();ws.alive=true;ws.on('pong',()=>ws.alive=true);let windowAt=Date.now(),count=0;
 ws.on('message',raw=>{try{if(Date.now()-windowAt>1000){windowAt=Date.now();count=0;}if(++count>30)return;const m=JSON.parse(raw);let r=rooms.get(ws.room),p=r?.players.find(p=>p.id===ws.id);
 if(m.type==='resume'){if(r)return;const room=rooms.get(String(m.code)),player=room?.players.find(q=>q.token===m.token&&typeof m.token==='string');if(!player||(player.disconnectedAt&&Date.now()-player.disconnectedAt>=30000))return send(ws,{type:'resume_failed'});const old=player.ws;if(old&&old!==ws){old.room=null;old.close(4001,'Session replaced');}player.ws=ws;player.disconnectedAt=0;ws.id=player.id;ws.room=room.code;resumeClock(room);send(ws,{type:'session',code:room.code,token:player.token});state(room);return;}
 if(m.type==='create'||m.type==='join'){if(r)return;const name=String(m.name||'펭귄').trim().slice(0,16)||'펭귄';if(m.type==='create'){if(rooms.size>=500)return send(ws,{type:'error',message:'서버가 가득 찼어요.'});let code;do{code=randomBytes(3).toString('hex').toUpperCase();}while(rooms.has(code));r={code,mode:m.mode===4?4:2,players:[],phase:'lobby',bodies:[],score:[0,0],aims:new Map(),endAt:0,deadline:0};rooms.set(code,r);}else r=rooms.get(String(m.code).toUpperCase());if(!r||r.phase!=='lobby'||r.pausedAt||r.players.length>=r.mode)return send(ws,{type:'error',message:'참가 가능한 방이 아니에요. 코드를 확인해 주세요.'});const team=r.players.filter(p=>p.team===0).length<=r.players.filter(p=>p.team===1).length?0:1;const token=randomBytes(32).toString('hex');r.players.push({id:ws.id,ws,name,team,ready:false,token,disconnectedAt:0});ws.room=r.code;send(ws,{type:'session',code:r.code,token});state(r);return;}
 if(!r||!p)return;
 if(m.type==='leave'){leave(ws);return send(ws,{type:'left'});}
 if(r.pausedAt)return;
 if(m.type==='team'&&r.phase==='lobby'){const t=m.team===1?1:0;if(r.players.filter(q=>q.team===t).length<r.mode/2){p.team=t;r.players.forEach(q=>q.ready=false);}}
 if(m.type==='ready'&&r.phase==='lobby'){p.ready=!p.ready;if(r.players.length===r.mode&&r.players.every(p=>p.ready)&&r.players.filter(p=>p.team===0).length===r.mode/2)start(r);}
 if(m.type==='rematch'&&r.phase==='done'){r.phase='lobby';r.players.forEach(p=>p.ready=false);r.bodies=[];r.aims.clear();}
 if(m.type==='aim'&&r.phase==='aim'&&Date.now()<r.deadline&&!r.aims.has(p.id)&&Number.isFinite(m.x)&&Number.isFinite(m.y)){const len=Math.hypot(m.x,m.y),scale=Math.max(1,len);r.aims.set(p.id,{x:m.x/scale,y:m.y/scale});if(r.aims.size===r.players.length)launch(r);}
 state(r);
 }catch{send(ws,{type:'error',message:'요청을 처리할 수 없어요.'});}});ws.on('close',()=>disconnect(ws));ws.on('error',()=>{});
});
let ticks=0;setInterval(()=>{const now=Date.now();for(const r of rooms.values()){const expired=r.players.filter(p=>p.disconnectedAt&&now-p.disconnectedAt>=30000);if(expired.length){r.players=r.players.filter(p=>!expired.includes(p));if(!r.players.length){rooms.delete(r.code);continue;}r.phase='lobby';r.bodies=[];r.aims.clear();r.players.forEach(p=>p.ready=false);resumeClock(r);state(r);}if(r.pausedAt){if(ticks%30===0)state(r);continue;}if(r.phase==='aim'&&now>=r.deadline)launch(r);if(r.phase==='move'){let goal=null;for(let i=0;i<2&&goal===null;i++)goal=step(r.bodies,1/120);if(goal!==null){r.score[goal]++;r.bodies=setup(r.players);}if(goal!==null||now>=r.deadline||r.bodies.every(b=>Math.hypot(b.vx,b.vy)<8)){r.bodies.forEach(b=>{b.vx=0;b.vy=0;});if(Math.max(...r.score)>=3||(now>=r.endAt&&r.score[0]!==r.score[1])){r.phase='done';r.winner=r.score[0]>r.score[1]?0:1;}else aimPhase(r);}}if(ticks%3===0&&r.phase!=='lobby')state(r);}ticks++;},1000/60);
setInterval(()=>{for(const ws of wss.clients){if(!ws.alive){ws.terminate();continue;}ws.alive=false;ws.ping();}},5000).unref();
server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('Penguin Soccer listening'));
process.on('SIGTERM',()=>{wss.clients.forEach(ws=>ws.close(1001,'Server shutting down'));server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),3000).unref();});
